### PR TITLE
add advanced-r tutorial details

### PR DESCRIPTION
**Pull request by mitchelloharawild**
- [x] Update index.html
- [x] Add details to tutorial_PM1.html
- [x] Add hero image and opengraph tags for social media previews
- [x] Create workshop website (https://workshop.nectric.com.au/advr-wombat24/)
- [x] Rework title (help wanted)

**Tutorial title**

I think 'Advancing your R skills' could be misconstrued as a basic-intermediate workshop about improving R skills.
Whereas what I'm giving is intermediate-advanced, loosely based on some topics in Hadley's Advanced R book (more details described on the website).

Perhaps 'Advanced R for Analysts'?

I'm trying to keep the workshop a bit fun and light, focusing on 'advanced tips and tricks for R users' instead of 'advanced R for programmers' - hence using 'analysts' in the title.
More suggestions are welcomed

### CODE REVIEW

**Comment by dicook** [comment]
I like "advanced tips and tricks for R users"

**Comment by dicook** [comment]
Or "advanced R tips and tricks for analysts"

**Comment by dicook** [comment]
happy for you to approve your pull requests, btw

**Comment by mitchelloharawild** [comment]
I think I like "Advanced R tips and tricks" - I'll play around with it some more :+1:

**Comment by mitchelloharawild** [comment]
I've went with "Advanced R Tips and Tricks", if you could please:
- [x] Update the tutorial title on humanitix
- [x] Update my name on humanitix to "Mitchell O'Hara-Wild"
- [x] Merge this PR when done

Thanks!

**Pull request merged**
